"""
Test script for PDF generation functionality
Tests the format_analysis_to_document() and generate_pdf_report() functions
"""

import sys
from pathlib import Path
from datetime import datetime

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

# Import the functions from Document_Analysis page
from fpdf import FPDF
from fpdf.enums import XPos, YPos
import io


def format_analysis_to_document(analysis_result: dict, document_info: dict) -> str:
    """Test version of format function"""
    document = []
    agent_results = analysis_result.get('analysis_results', {})

    # Header
    document.append(f"COMPREHENSIVE ANALYSIS REPORT")
    document.append(f"\n{document_info.get('name', 'Research Paper')}")
    document.append(f"\nAnalysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    document.append(f"Document Size: {document_info.get('size', 0):.2f} MB")
    document.append(f"Format: {document_info.get('format', 'PDF').lstrip('.').upper()}")
    document.append("\n" + "="*80 + "\n")

    # Add test content
    document.append("\nEXECUTIVE SUMMARY\n" + "="*80)
    document.append("\nThis is a test executive summary with detailed multi-paragraph content. " +
                   "The research demonstrates significant advances in the field of artificial intelligence. " +
                   "Key findings include improved accuracy and efficiency in model performance.")

    document.append("\n\n\nRESEARCH PROBLEM & CONTEXT\n" + "="*80)
    document.append("\n\nThe central research problem addressed in this paper is: How to improve " +
                   "neural network efficiency while maintaining accuracy.")

    document.append("\n\n\nMETHODOLOGY\n" + "="*80)
    document.append("\n\nResearch Design: This study employs a mixed-methods approach combining " +
                   "quantitative experiments with qualitative analysis.")

    # Footer
    document.append("\n\n" + "="*80)
    document.append("\nReport generated by Research Paper Discovery System")
    document.append("Multi-Agent Analysis Framework")
    document.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

    return "\n".join(document)


def generate_pdf_report(formatted_content: str, document_name: str) -> bytes:
    """Generate PDF from formatted content"""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Add first page
    pdf.add_page()

    # Set up fonts
    pdf.set_font('Helvetica', 'B', 20)

    # Title page
    pdf.cell(0, 20, 'COMPREHENSIVE ANALYSIS REPORT', new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    pdf.ln(10)

    # Document name - handle encoding
    pdf.set_font('Helvetica', 'B', 14)
    safe_doc_name = document_name.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, safe_doc_name, align='C')
    pdf.ln(5)

    # Date
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    pdf.ln(10)

    # System info
    pdf.set_font('Helvetica', 'I', 9)
    pdf.multi_cell(0, 5, 'Report generated by Research Paper Discovery System\nMulti-Agent Analysis Framework', align='C')

    # Add new page for content
    pdf.add_page()

    # Process content line by line with better error handling
    lines = formatted_content.split('\n')

    for line in lines:
        try:
            # Skip completely empty lines
            if not line or not line.strip():
                pdf.ln(3)
                continue

            # Skip separator lines (=== lines)
            if line.strip().startswith('='):
                pdf.ln(2)
                continue

            # Check if line is a section header (all uppercase)
            if line.strip() and line.strip().isupper() and not line.strip().startswith('**'):
                # Section header
                pdf.set_font('Helvetica', 'B', 13)
                pdf.set_text_color(0, 51, 102)  # Dark blue
                safe_header = line.strip().encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(0, 8, safe_header, align='L')
                pdf.set_text_color(0, 0, 0)  # Reset to black
                pdf.ln(3)
                continue

            # Regular content
            pdf.set_font('Helvetica', '', 11)

            # Clean and encode the line
            cleaned_line = line.strip()
            if not cleaned_line:
                continue

            # Handle encoding
            try:
                safe_line = cleaned_line.encode('latin-1', 'replace').decode('latin-1')
            except Exception:
                safe_line = cleaned_line.encode('ascii', 'ignore').decode('ascii')

            # Add the line
            if safe_line:
                pdf.multi_cell(0, 6, safe_line)

        except Exception as e:
            # Skip problematic lines but continue processing
            print(f"Warning: Skipped line due to error: {e}")
            continue

    # Get PDF as bytes
    pdf_bytes = pdf.output()

    # Return as bytes (fpdf2 returns bytes or bytearray)
    if isinstance(pdf_bytes, (bytes, bytearray)):
        return bytes(pdf_bytes)
    else:
        # Fallback for string (older versions)
        return pdf_bytes.encode('latin-1')


def test_pdf_generation():
    """Test the PDF generation process"""
    print("="*60)
    print("PDF GENERATION TEST")
    print("="*60)
    print()

    # Test 1: Format analysis to document
    print("Test 1: Testing format_analysis_to_document()...")
    try:
        test_analysis = {
            'analysis_results': {},
            'metrics': {
                'successful_agents': 11,
                'total_agents': 11,
                'total_time': 45.5
            }
        }

        test_doc_info = {
            'name': 'Test_Research_Paper.pdf',
            'size': 2.5,
            'format': 'pdf'
        }

        formatted_content = format_analysis_to_document(test_analysis, test_doc_info)

        if len(formatted_content) > 0:
            print("✅ format_analysis_to_document() works correctly")
            print(f"   Generated {len(formatted_content)} characters of content")
        else:
            print("❌ format_analysis_to_document() returned empty content")
            return False

    except Exception as e:
        print(f"❌ format_analysis_to_document() failed: {e}")
        import traceback
        traceback.print_exc()
        return False

    print()

    # Test 2: Generate PDF
    print("Test 2: Testing generate_pdf_report()...")
    try:
        pdf_bytes = generate_pdf_report(formatted_content, 'Test_Research_Paper.pdf')

        if isinstance(pdf_bytes, bytes) and len(pdf_bytes) > 0:
            print("✅ generate_pdf_report() works correctly")
            print(f"   Generated PDF with {len(pdf_bytes)} bytes")

            # Test 3: Save PDF to file
            print()
            print("Test 3: Saving PDF to file...")
            output_path = Path("test_generated_report.pdf")
            with open(output_path, 'wb') as f:
                f.write(pdf_bytes)

            if output_path.exists():
                print(f"✅ PDF saved successfully to {output_path}")
                print(f"   File size: {output_path.stat().st_size} bytes")
            else:
                print("❌ Failed to save PDF file")
                return False

        else:
            print("❌ generate_pdf_report() returned invalid data")
            return False

    except Exception as e:
        print(f"❌ generate_pdf_report() failed: {e}")
        import traceback
        traceback.print_exc()
        return False

    print()
    print("="*60)
    print("✅ ALL PDF GENERATION TESTS PASSED")
    print("="*60)
    print()
    print("Next steps:")
    print("1. Open test_generated_report.pdf to verify formatting")
    print("2. Check that all sections are properly formatted")
    print("3. Verify that fonts and spacing look correct")
    print()
    return True


if __name__ == "__main__":
    success = test_pdf_generation()
    sys.exit(0 if success else 1)
